---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I crave your mouth, your voice, your hair.  
Silent and starving, I prowl through the streets.  
Bread does not nourish me, dawn disrupts me, all day  
I hunt for the liquid measure of your steps.  

I hunger for your sleek laugh,  
your hands the color of a savage harvest,  
hunger for the pale stones of your fingernails,  
I want to eat your skin like a whole almond.  

I want to eat the sunbeam flaring in your lovely body,  
the sovereign nose of your arrogant face,  
I want to eat the fleeting shade of your lashes,  

and I pace around hungry, sniffing the twilight,  
hunting for you, for your hot heart,  
like a puma in the barrens of Quitratue.  
